// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using mijn_recepten.Contexts;

namespace mijn_recepten.Migrations
{
    [DbContext(typeof(MainContext))]
    [Migration("20181101165727_updateFavorite")]
    partial class updateFavorite
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-preview3-35497")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("mijn_recepten.Models.DB.Favorite", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("recipeId");

                    b.Property<int>("userId");

                    b.HasKey("id");

                    b.ToTable("favorites");
                });

            modelBuilder.Entity("mijn_recepten.Models.DB.Ingredient", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ingredient");

                    b.Property<int>("recipeId");

                    b.HasKey("id");

                    b.HasIndex("recipeId");

                    b.ToTable("ingredients");
                });

            modelBuilder.Entity("mijn_recepten.Models.DB.Link", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("link");

                    b.Property<int>("recipeId");

                    b.HasKey("id");

                    b.HasIndex("recipeId");

                    b.ToTable("links");
                });

            modelBuilder.Entity("mijn_recepten.Models.DB.Recipe", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("name");

                    b.Property<string>("persons");

                    b.Property<string>("requester");

                    b.Property<string>("videoId");

                    b.HasKey("id");

                    b.ToTable("recipes");
                });

            modelBuilder.Entity("mijn_recepten.Models.DB.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("email");

                    b.Property<string>("name");

                    b.Property<string>("passwordHash");

                    b.Property<string>("passwordSalt");

                    b.Property<string>("role");

                    b.HasKey("id");

                    b.HasIndex("email")
                        .IsUnique();

                    b.ToTable("users");
                });

            modelBuilder.Entity("mijn_recepten.Models.DB.Ingredient", b =>
                {
                    b.HasOne("mijn_recepten.Models.DB.Recipe")
                        .WithMany("ingredients")
                        .HasForeignKey("recipeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("mijn_recepten.Models.DB.Link", b =>
                {
                    b.HasOne("mijn_recepten.Models.DB.Recipe")
                        .WithMany("links")
                        .HasForeignKey("recipeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
